[ids]

# Logitech Marble Mouse
046d:c402:d6305b1e

[main]
# Tap (<200ms): Middle Mouse / Hold (>200ms): Right Mouse (Enables KDE Trackball Scroll)
rightmouse = timeout(rightmouse, 200, middlemouse)

# Simultaneous Click: Back
leftmouse+rightmouse = back
