# トリガーキー
TriggerKey=
# 現在の入力コンテキストのみのトリガーキー
TriggerKeyLocal=
# 現在の入力コンテキストのみをN番目の入力メソッドに切り替えるホットキー
SwitchKeyLocal=

[SwitchKey]
0=Control+Alt+Shift+Super+F1
1=Control+Alt+Shift+Super+F2
2=Control+Alt+Shift+Super+F3
3=Control+Alt+Shift+Super+F4

